# -*- coding: utf-8 -*-
"""app_pricing and inventory optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFBrqH8OBPNlnqd7F39L69COcbNzQb9G
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Page config
st.set_page_config(
    page_title="Pricing & Inventory Optimization",
    layout="wide"
)

st.title("Pricing & Inventory Optimization Dashboard")
st.markdown("""
This dashboard evaluates pricing strategies by combining **demand response, revenue impact, and inventory feasibility**.
It is designed for executive decision-making.
""")

# Load data
scenario_df = pd.read_csv("data/scenario_summary.csv")
category_df = pd.read_csv("data/category_decision_table.csv")
elasticity_df = pd.read_csv("data/elasticity_risk_table.csv")

# -----------------------
# Scenario Selector
# -----------------------
scenario = st.selectbox(
    "Select Pricing Scenario",
    scenario_df["Scenario"].unique()
)

selected = scenario_df[scenario_df["Scenario"] == scenario].iloc[0]

# -----------------------
# KPI Section
# -----------------------
st.subheader("Executive KPIs")

col1, col2, col3 = st.columns(3)

col1.metric(
    "Feasible Revenue",
    f"${selected['Feasible_Revenue']:,.0f}"
)

col2.metric(
    "Theoretical Revenue",
    f"${selected['Theoretical_Revenue']:,.0f}"
)

col3.metric(
    "Stockout Risk",
    selected["Stockout_Risk"]
)

# -----------------------
# Revenue Comparison Chart
# -----------------------
st.subheader("Scenario Revenue Comparison")

fig, ax = plt.subplots()
ax.bar(
    scenario_df["Scenario"],
    scenario_df["Feasible_Revenue"]
)
ax.set_ylabel("Revenue")
ax.set_title("Feasible Revenue by Pricing Scenario")
st.pyplot(fig)

# -----------------------
# Category Strategy Table
# -----------------------
st.subheader("Category-Level Pricing Decisions")
st.dataframe(
    category_df,
    use_container_width=True
)

# -----------------------
# Elasticity vs Risk
# -----------------------
st.subheader("Elasticity vs Inventory Risk")

fig, ax = plt.subplots()

for band in elasticity_df["elasticity_band"].unique():
    subset = elasticity_df[elasticity_df["elasticity_band"] == band]
    ax.scatter(
        subset["price_elasticity_proxy"],
        subset["stock_minus_10"],
        label=band
    )

ax.set_xlabel("Price Elasticity (Proxy)")
ax.set_ylabel("Stockout Rate (-10% Price)")
ax.set_title("Elasticity vs Inventory Risk")
ax.legend()
st.pyplot(fig)

# -----------------------
# Recommendations
# -----------------------
st.subheader("Executive Recommendations")

st.markdown("""
**Key Takeaways**
- Aggressive discounts generate high demand but introduce significant stockout risk.
- Revenue-maximizing prices are not always operationally feasible.
- Moderate pricing strategies balance profitability and execution.

**Business Recommendation**
> Optimize for **realized revenue**, not theoretical demand.
> Pricing decisions must be aligned with inventory readiness.
""")